name = "casino-content-admin"
compatibility_date = "2024-02-01"

[vars]
CF_ACCOUNT_ID = "cd4628cb46169b384a110e86fa36a731"
CF_ACCOUNT_HASH = "ZBOPrnpcIfgpzV8AiUbS2Q"

# Development environment variables
[env.development]
vars = { ENVIRONMENT = "development" }

# Production environment variables
[env.production]
vars = { ENVIRONMENT = "production" }